"""Property-based tests for the strict pgmq surface (sync ``PGMQueue``).

Each property exercises a contract that should hold for ANY input
generated by hypothesis (within the strategies' bounds). Properties
are kept identical in semantics to the jqwik suite under
``clients/java/src/test/java/.../client/PropertyIT.java`` so the two
clients have a shared invariant set.

Strategy notes
--------------

* Payloads are JSON-safe dicts only: keys are short non-empty strings,
  values are scalars or recursively-bounded dicts. We deliberately avoid
  unbounded recursion, NaN/inf floats, and very wide strings so each
  example survives a round trip through SQL Server's NVARCHAR(MAX) +
  ISJSON CHECK constraint without surprises.
* Each property uses its own queue (`unique_queue_name`) and drops it on
  exit so examples are isolated. Hypothesis re-runs each property up to
  ``max_examples`` times against the same database — the queue lifecycle
  must therefore live inside the property, not the pytest fixture.
* Budgets: ``max_examples=30`` per property, ``deadline=10000`` ms per
  example. Each example is a real DB round trip via testcontainers; with
  ~10 properties this lands at well under 5 minutes wall-time per CI run.
"""

from __future__ import annotations

from typing import Any

import hypothesis.strategies as hst
import pytest
from hypothesis import HealthCheck, given, settings

from sqlmq import PGMQueue
from tests.conftest import unique_queue_name


# ---------------------------------------------------------------- strategies

# JSON-safe leaf values. We pick float bounds carefully to avoid the
# round-trip-loss surprise: SQL Server's JSON storage round-trips IEEE-754
# doubles exactly, but we still skip NaN/inf because Python's ``json``
# refuses to serialize them.
json_scalars = hst.one_of(
    hst.integers(min_value=-1_000_000, max_value=1_000_000),
    hst.floats(allow_nan=False, allow_infinity=False, width=32),
    hst.text(max_size=64),
    hst.booleans(),
    hst.none(),
)

# Recursive dicts: keys are short, non-empty, ASCII-text-ish strings to
# stay well inside the 60-char queue-name regex world (which is unrelated
# to message keys, but keeps us out of pathological-key territory).
json_dict = hst.recursive(
    json_scalars,
    lambda children: hst.dictionaries(
        hst.text(min_size=1, max_size=16), children, max_size=8
    ),
    max_leaves=10,
).filter(lambda x: isinstance(x, dict))

# Lists of dicts for batch properties.
json_dict_list_small = hst.lists(json_dict, min_size=1, max_size=20)
json_dict_list_purge = hst.lists(json_dict, min_size=1, max_size=50)

# Unknown ids: positive ints in a range we'll never realistically allocate
# inside a single test (msg_ids start at 1, so 10**9+ is safe).
unknown_id_list = hst.lists(
    hst.integers(min_value=1_000_000_000, max_value=2_000_000_000),
    min_size=1,
    max_size=20,
    unique=True,
)


# ---------------------------------------------------------------- shared settings

PROPERTY_SETTINGS = settings(
    max_examples=30,
    deadline=10_000,  # 10 s per example: each example talks to SQL Server
    suppress_health_check=[
        # The session-scoped container fixture and per-example queue
        # create/drop is intentional; suppress hypothesis' warning about
        # function-scoped fixture reuse across examples.
        HealthCheck.function_scoped_fixture,
    ],
)


def _with_queue(client: PGMQueue):
    """Create a fresh queue and return its name; caller drops it.

    Convenience to keep each property a single logical block while still
    isolating examples: each invocation gets its own queue.
    """
    name = unique_queue_name()
    client.create_queue(name)
    return name


# ---------------------------------------------------------------- properties

@PROPERTY_SETTINGS
@given(message=json_dict)
def test_p1_send_read_round_trip_preserves_message(queue_factory, message):
    """P1: send then read returns the original payload byte-for-byte (after JSON)."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        q.send(name, message)
        m = q.read(name, vt=30)
        assert m is not None
        assert m.message == message
    finally:
        q.drop_queue(name)


@PROPERTY_SETTINGS
@given(messages=hst.lists(json_dict, min_size=2, max_size=20))
def test_p2_monotonic_msg_ids_per_queue(queue_factory, messages):
    """P2: msg_ids issued by send() within one queue are strictly increasing
    and unique. Validates V010's per-queue applock serialization."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        ids = [q.send(name, m) for m in messages]
        assert ids == sorted(ids), f"ids not monotonic: {ids}"
        assert len(set(ids)) == len(ids), f"ids contain duplicates: {ids}"
    finally:
        q.drop_queue(name)


@PROPERTY_SETTINGS
@given(message=json_dict)
def test_p3_vt_honored_within_session(queue_factory, message):
    """P3: a read with vt=60s hides the message; an immediate second read
    must return None (the message is in flight, vt has not expired)."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        q.send(name, message)
        first = q.read(name, vt=60)
        assert first is not None
        second = q.read(name, vt=60)
        assert second is None, f"second read should be empty, got {second}"
    finally:
        q.drop_queue(name)


@PROPERTY_SETTINGS
@given(messages=json_dict_list_small)
def test_p4_delete_then_read_returns_none(queue_factory, messages):
    """P4: after delete_batch on every id, read returns None."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        ids = [q.send(name, m) for m in messages]
        deleted = q.delete_batch(name, ids)
        # All requested ids should have been deleted (they all existed).
        assert sorted(deleted) == sorted(ids)
        assert q.read(name, vt=30) is None
    finally:
        q.drop_queue(name)


@PROPERTY_SETTINGS
@given(message=json_dict)
def test_p5_archive_moves_rather_than_copies(queue_factory, message):
    """P5: archive removes from the active queue (queue_length drops to 0)."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        msg_id = q.send(name, message)
        # Claim it so we know the id is real before archiving.
        first = q.read(name, vt=30)
        assert first is not None and first.msg_id == msg_id
        assert q.archive(name, msg_id) is True
        assert q.read(name, vt=30) is None
        assert q.metrics(name).queue_length == 0
    finally:
        q.drop_queue(name)


@PROPERTY_SETTINGS
@given(messages=json_dict_list_purge)
def test_p6_purge_clears_active_queue(queue_factory, messages):
    """P6: purge returns the count it deleted, then queue is empty."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        for m in messages:
            q.send(name, m)
        count = q.purge(name)
        assert count == len(messages)
        assert q.read(name, vt=30) is None
        assert q.metrics(name).queue_length == 0
    finally:
        q.drop_queue(name)


@PROPERTY_SETTINGS
@given(messages=json_dict_list_small)
def test_p7_send_batch_returns_n_ids_in_caller_order(queue_factory, messages):
    """P7: send_batch returns one id per message, monotonic (caller order)."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        ids = q.send_batch(name, messages)
        assert len(ids) == len(messages)
        assert ids == sorted(ids)
    finally:
        q.drop_queue(name)


@PROPERTY_SETTINGS
@given(unknown_ids=unknown_id_list)
def test_p8_delete_batch_with_unknown_ids_returns_empty(queue_factory, unknown_ids):
    """P8: delete_batch on a queue that contains none of the requested ids
    returns an empty list (no false positives in the deleted-id contract)."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        result = q.delete_batch(name, unknown_ids)
        assert result == []
    finally:
        q.drop_queue(name)


@PROPERTY_SETTINGS
@given(headers=hst.dictionaries(
    hst.text(min_size=1, max_size=16),
    json_scalars,
    min_size=1,
    max_size=8,
))
def test_p9_headers_round_trip_when_sent(queue_factory, headers):
    """P9 (sqlmq extension): headers passed to send round-trip via
    ``Message.headers`` after read."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        q.send(name, {"v": 1}, headers=headers)
        m = q.read(name, vt=30)
        assert m is not None
        assert m.headers == headers
    finally:
        q.drop_queue(name)


def test_p10_read_on_empty_queue_returns_none_or_empty_list(queue_factory):
    """P10 (sanity, not strictly property-based): a fresh queue's read()
    returns None and read_batch() returns []. Included in the property
    suite for completeness — no input generation needed."""
    q = queue_factory()
    name = _with_queue(q)
    try:
        assert q.read(name) is None
        assert q.read_batch(name, vt=30, batch_size=10) == []
    finally:
        q.drop_queue(name)
